// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlayerManagement.DAL;

#nullable disable

namespace PlayerManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250523100550_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlayerManagement.Models.Citizenship", b =>
                {
                    b.Property<int>("CitizenshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CitizenshipId"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CitizenshipId");

                    b.ToTable("Citizenships");

                    b.HasData(
                        new
                        {
                            CitizenshipId = 1,
                            CountryName = "Bangladesh"
                        },
                        new
                        {
                            CitizenshipId = 2,
                            CountryName = "Australia"
                        },
                        new
                        {
                            CitizenshipId = 3,
                            CountryName = "New Zealand"
                        });
                });

            modelBuilder.Entity("PlayerManagement.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<int>("CitizenshipId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOverseas")
                        .HasColumnType("bit");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SigningDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SigningFee")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PlayerId");

                    b.HasIndex("CitizenshipId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("PlayerManagement.Models.PlayerSkill", b =>
                {
                    b.Property<int>("PlayerSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerSkillId"));

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("SkillLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlayerSkillId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerSkills");
                });

            modelBuilder.Entity("PlayerManagement.Models.Player", b =>
                {
                    b.HasOne("PlayerManagement.Models.Citizenship", "Citizenships")
                        .WithMany("Players")
                        .HasForeignKey("CitizenshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Citizenships");
                });

            modelBuilder.Entity("PlayerManagement.Models.PlayerSkill", b =>
                {
                    b.HasOne("PlayerManagement.Models.Player", "Players")
                        .WithMany("PlayerSkills")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Players");
                });

            modelBuilder.Entity("PlayerManagement.Models.Citizenship", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("PlayerManagement.Models.Player", b =>
                {
                    b.Navigation("PlayerSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
